version: '2'
services:
  parity-system:
    build: 'parity-system'
    ports:
      - '4000:4000'
      - '6000:6000'
  parity-fix:
    build: 'parity-fix'
    ports:
      - '4010:4010'
  market-data-gateway:
    build: 'nassau-soupbintcp-gateway'
    ports:
      - '5000:5000'
